apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sgsallowoutgoing.pet2cattle.com
spec:
  group: pet2cattle.com
  names:
    kind: SGAllowOutgoing
    plural: sgsallowoutgoing
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              parameters:
                type: object
                properties:
                  region:
                    type: string
                required:
                - region
            required:
            - parameters
