
# resource "aws_security_group" "pod_sg" {
#   name        = "xplane-xplanesg"
#   description = "xplane SG test"
#   vpc_id      = var.vpc_id
# }

apiVersion: ec2.aws.jet.crossplane.io/v1alpha2
kind: SecurityGroup
metadata:
  name: 'xplanesg'
  labels:
    sgname: 'xplanesg'
spec:
  forProvider:
    name: 'xplane-xplanesg'
    region: 'us-west-2'
    description: 'xplane SG test'
    vpcId: 'vpc-1234abcd'
  providerConfigRef:
    name: 'aws-jetprovider-config'